name: CI & Publish

on:
  pull_request:  # PR 발생 시 테스트 실행
    branches:
      - main
  push:  # main 브랜치에 push 시 릴리즈 진행
    branches:
      - main

jobs:
  # Job 1: Run tests on pull request
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Codecov 토큰
          files: core/build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: codecov-report
          fail_ci_if_error: true

  # Job 2: Publish library on main branch
  release:
    name: Release and Publish
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Publish Library
        run: ./gradlew publish